const products = [
  {
    id: 1,
    name:   "شمعه معطره بشكل زهره",
    nameEn: "Flower-Shaped Scented Candle",
    desc:   "أضيفي لمسة من الأناقة والدفء إلى منزلك مع هذه الشمعة المعطرة المصممة على شكل زهرة رائعة بتفاصيل دقيقة وجذابة. تمتاز بلونها الهادئ الذي يضفي إحساسًا بالراحة والسكينة، لتكون خيارًا مثاليًا للاسترخاء أو لتزيين أي مساحة في المنزل.",
    descEn: "Add a touch of elegance and warmth to your home with this beautifully designed flower-shaped scented candle. Its soft color creates a calming ambiance, making it perfect for relaxation or as a home decoration piece.",
    price: 20,
    stock: 0,
    emoji: "🕯️",
    image: "images/flower-candle.jpeg",
    images: ["images/flower-candle.jpeg"],
    imgFilter: "brightness(1.05) contrast(1.05) saturate(1.15)",
    imgPosition: "center center",
  },
  {
    id: 2,
    name:   "صندوق لا تحزن",
    nameEn: "Don't Grieve Box",
    desc:   "صندوق خشبي أنيق محفور يدوياً بعبارة 'لا تحزن'، هدية ملهمة ومواسية تحمل رسالة دافئة لشخص عزيز في لحظات الحزن والضيق. مصنوع بحرفية عالية وتصميم شرقي فاخر.",
    descEn: "An elegant hand-engraved wooden box with the phrase 'Don't Grieve' — a comforting and inspiring gift that carries a warm message for a loved one in moments of grief. Crafted with high quality and a luxurious oriental design.",
    price: 170,
    stock: 0,
    emoji: "👜",
    image: "images/dont-cry-box.jpeg",
    images: [
      "images/dont-cry-box.jpeg",
      "images/dont-grieve-box/WhatsApp Image 2026-04-02 at 14.47.58.jpeg",
      "images/dont-grieve-box/WhatsApp Image 2026-04-02 at 14.47.59.jpeg",
      "images/dont-grieve-box/WhatsApp Image 2026-04-02 at 14.48.00.jpeg",
    ],
    variants: [
      { key: "box",     label: "الصندوق فقط",      labelEn: "Box Only",      price: 100 },
      { key: "package", label: "الباقة الكاملة",    labelEn: "Full Package",  price: 170 },
    ],
    contents: [
      "بطاقات تحفيزية لكلمات تُضيء يومك",
      "كوب زجاجي مزين بالزهور المجففة ليضيف لمسة جمال لأوقاتك",
      "إكسسوارات خشبية محفورة بعبارات مميزة",
    ],
    contentsEn: [
      "Motivational cards with words that brighten your day",
      "A glass cup decorated with dried flowers to add beauty to your moments",
      "Wooden accessories engraved with special phrases",
    ],
  },
  {
    id: 3,
    name:   "صندوق كن انت",
    nameEn: "Be Yourself Box",
    desc:   "صندوق خشبي أنيق محفور يدوياً بعبارة كن أنت، لأنك فريد ومميز. هدية ملهمة مليئة بالقوة والإيجابية، بتصميم شرقي فاخر ومصنوع بحرفية عالية. لمسة تراثية بروح عصرية، مثالية لشخص عزيز.",
    descEn: "A beautifully hand-engraved wooden box with the phrase 'Be Yourself' — because you are unique. An inspiring gift full of positivity and strength, with a luxurious oriental design and high craftsmanship. A heritage touch with a modern spirit, perfect for someone special.",
    price: 120,
    stock: 20,
    emoji: "☕",
    image: "images/beyourself-box.jpeg",
    variants: [
      { key: "box",     label: "الصندوق فقط",      labelEn: "Box Only",      price: 70  },
      { key: "package", label: "الباقة الكاملة",    labelEn: "Full Package",  price: 120 },
    ],
    contents: [
      "بطاقات تحفيزية تساعدك على تحقيق أهدافك بثقة",
      "شموع برائحة دافئة لإضافة لمسة من الاسترخاء والراحة",
      "ملصقات مميزة لتزيين يومياتك برسائل إيجابية",
      "تعليقة مميزة للسيارة",
    ],
    contentsEn: [
      "Motivational cards to help you achieve your goals with confidence",
      "Warm scented candles to add a touch of relaxation and comfort",
      "Special stickers to decorate your daily life with positive messages",
      "A unique car hanging accessory",
    ],
    images: [
      "images/beyourself-box.jpeg",
      "images/be-yourself-box/WhatsApp Image 2026-04-02 at 14.46.43.jpeg",
      "images/be-yourself-box/WhatsApp Image 2026-04-02 at 14.46.44.jpeg",
      "images/be-yourself-box/WhatsApp Image 2026-04-02 at 14.46.45.jpeg",
    ],
  },
  {
    id: 4,
    name:   "طقم خزف مربع – صحن كبير مع 6 أوعية",
    nameEn: "Square Ceramic Set – Large Plate with 6 Bowls",
    desc:   "طقم خزف أصيل مصنوع ومرسوم يدوياً من مدينة الخليل، يتألف من صحن مربع كبير ومعه 6 أطباق صغيرة متناسقة. يتميز بزخارف زهرية ملونة بألوان زاهية (أزرق، أحمر، أخضر، أصفر) على خلفية بيضاء ناصعة مع إطار أزرق داكن أنيق. مثالي للتقديم والضيافة وإضفاء لمسة تراثية على مائدتك. يصلح هدية فاخرة أو قطعة ديكور مميزة.",
    descEn: "An authentic handmade and hand-painted ceramic set from the city of Hebron, consisting of a large square plate with 6 matching small bowls. Features colorful floral patterns (blue, red, green, yellow) on a pure white background with an elegant dark blue border. Ideal for serving, hosting, and adding a heritage touch to your table. Perfect as a luxury gift or decorative piece.",
    price: 200,
    stock: 0,
    emoji: "🏺",
    image: "images/ceramic-set-square.jpeg",
    images: ["images/ceramic-set-square.jpeg"],
    imgFilter: "brightness(1.05) contrast(1.08) saturate(1.15)",
    imgPosition: "center center",
  },
  {
    id: 5,
    name:   "طقم صناديق موزاييك – 3 مقاسات + صينية ثمانية",
    nameEn: "Mosaic Boxes Set – 3 Sizes + Octagonal Tray",
    desc:   "طقم فريد من صناديق خشبية مثمّنة الشكل مزيّنة بفن الموزاييك الأصيل، وهو فن تطعيم الخشب بالخشب المتعدد الألوان وفق أنماط هندسية إسلامية دقيقة. يضم الطقم صينية ثمانية كبيرة وثلاثة صناديق بمقاسات مختلفة (صغير، وسط، كبير). تحفة حرفية تجمع بين الجمال والاستخدام العملي للتخزين والهدايا.",
    descEn: "A unique set of octagonal wooden boxes adorned with authentic mosaic art — the craft of inlaying wood with multi-colored wood in precise Islamic geometric patterns. The set includes a large octagonal tray and three boxes in different sizes (small, medium, large). A masterpiece that combines beauty with practical use for storage and gifting.",
    price: 350,
    stock: 0,
    emoji: "🎁",
    image: "images/mosaic-boxes-set.jpeg",
    images: ["images/mosaic-boxes-set.jpeg"],
    imgFilter: "brightness(1.25) contrast(1.12) saturate(1.2)",
    imgPosition: "center center",
  },
  {
    id: 6,
    name:   "طقم صواني موزاييك مثمن – مقاسان",
    nameEn: "Octagonal Mosaic Trays – 2 Sizes",
    desc:   "صينيتان خشبيتان مثمّنتا الشكل مطعّمتان بفن الموزاييك التقليدي بأنماط هندسية متداخلة بألوان البني والبيج والعاجي. صنعة يدوية عالية الدقة تعكس عراقة الحرفة. تستخدم للتقديم، الديكور، أو كهدية راقية.",
    descEn: "Two octagonal wooden trays inlaid with traditional mosaic art in interlocking geometric patterns of brown, beige, and ivory. High-precision handcraft reflecting the richness of the trade. Used for serving, decoration, or as an elegant gift.",
    price: 200,
    stock: 0,
    emoji: "🪵",
    image: "images/mosaic-tray-octagon.jpeg",
    images: ["images/mosaic-tray-octagon.jpeg"],
    imgFilter: "brightness(1.35) contrast(1.15) saturate(1.2)",
    imgPosition: "center center",
  },
  {
    id: 7,
    name:   "طقم صواني موزاييك مستطيل – 3 مقاسات متداخلة",
    nameEn: "Rectangular Mosaic Trays – 3 Nested Sizes",
    desc:   "ثلاث صواني خشبية مستطيلة تتدرج في الحجم، مصنوعة بتقنية التطعيم والموزاييك مع لمسات من الصدف. تحمل زخارف هندسية إسلامية بالغة الدقة بألوان دافئة. مثالية للاستخدام اليومي، التقديم، أو كتحفة ديكورية. تُجمع معاً لتوفير مساحة أو تُفرد للعرض.",
    descEn: "Three rectangular wooden trays graduated in size, crafted with inlay and mosaic technique with mother-of-pearl accents. They feature highly precise Islamic geometric patterns in warm colors. Perfect for daily use, serving, or as a decorative piece. Nest together to save space or display separately.",
    price: 200,
    stock: 0,
    emoji: "🪵",
    image: "images/mosaic-tray-rectangle.jpeg",
    images: ["images/mosaic-tray-rectangle.jpeg"],
    imgFilter: "brightness(1.15) contrast(1.1) saturate(1.15)",
    imgPosition: "center top",
  },
  {
    id: 8,
    name:   "طقم أطباق خزف – 3 مقاسات (صغير، وسط، كبير)",
    nameEn: "Ceramic Plates Set – 3 Sizes (Small, Medium, Large)",
    desc:   "ثلاثة أطباق خزفية مرسومة بالكامل باليد من مدينة الخليل، بزخارف زهرية ملونة بأسلوب تراثي أصيل على خلفية بيضاء وإطار أزرق داكن. تأتي بثلاثة مقاسات متناسقة لتناسب مختلف الاستخدامات. مناسبة للتقديم، العرض، أو كهدية ذات طابع تراثي مميز.",
    descEn: "Three fully hand-painted ceramic plates from the city of Hebron, with colorful floral patterns in authentic heritage style on a white background with a dark blue border. Available in three matching sizes to suit different uses. Suitable for serving, display, or as a heritage gift.",
    price: 180,
    stock: 0,
    emoji: "🏺",
    image: "images/ceramic-plates-set.jpeg",
    images: ["images/ceramic-plates-set.jpeg"],
    imgFilter: "brightness(1.08) contrast(1.08) saturate(1.2)",
    imgPosition: "center top",
  },
  {
    id: 9,
    name:   "زوج صحون خزف بيضاوي – رسم يدوي",
    nameEn: "Oval Ceramic Plates Pair – Hand Painted",
    desc:   "زوج من الصحون البيضاوية مصنوعة من الخزف الأصيل، رُسمت بالكامل باليد بزخارف زهرية متشابكة بألوان زاهية (أحمر، أزرق، برتقالي، أصفر، أخضر) على خلفية بيضاء ناصعة، مع إطار أزرق داكن مزخرف بنقوش عربية رفيعة. صنع يدوي 100% من حرفيي الخليل، ألوان ثابتة ومحروقة بالفرن. هدية راقية تحمل عبق التراث الأصيل.",
    descEn: "A pair of oval plates made from authentic ceramic, fully hand-painted with intricate floral patterns in vibrant colors (red, blue, orange, yellow, green) on a pure white background, with a dark blue border adorned with fine Arabic motifs. 100% handmade by Hebron artisans, with kiln-fired permanent colors. An elegant gift carrying the essence of authentic heritage.",
    price: 120,
    stock: 0,
    emoji: "🏺",
    image: "images/ceramic-oval-plates.jpeg",
    images: ["images/ceramic-oval-plates.jpeg"],
    imgFilter: "brightness(1.08) contrast(1.05) saturate(1.2)",
    imgPosition: "center top",
  },
];
